# Generated by Django 3.1.6 on 2021-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210207_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
