# Generated by Django 3.1.6 on 2021-02-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210207_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
